### ISSUE TITLE
User can submit a record

### ISSUE THREAD

**Issue by bryanvaldovinos** [bryanvaldovinos/final-project#1]
## ⚙️ Feature

Users will be able to submit a record that includes runner name, distance, and time for given distance.

## 📐 Functionality

User will submit a form containing information regarding name, distance, and time. Form will capture data and insert into table.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-07-27 at 4 03 06 PM](https://user-images.githubusercontent.com/103273265/181387136-fa046f6a-fbe3-44ac-b8c9-604309efc874.png)
![Screen Shot 2022-07-27 at 4 02 53 PM](https://user-images.githubusercontent.com/103273265/181387141-3ff8f7ad-8a1b-4655-9f9d-c8c02304ff53.png)
![Screen Shot 2022-07-27 at 4 02 42 PM](https://user-images.githubusercontent.com/103273265/181387146-d55a0c83-eb79-49f6-9b43-e7a1ebad79bf.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Account for insertion of runnerName, distance, and time

### ☁️ Server Tasks

- [ ] Make sure client can post to database and responses are returned with appropriate status codes/messages
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a form component
- [x] Form component should accept runnerName, distance, and time
- [x] submit button for the form
- [x] Create nav bar component to include application name 
- [x] Work css stylesheet to include color, shape, and positioning of components
- [ ] Create modal component with back button that reverts users to previous form 

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
